password = ""
base_path = ""
max_count = 99
[aliyun]
  [aliyun.mac2015]
    AccessKeyID = "AccessKeyID"
    AccessKeySecret = "AccessKeySecret"
    Region = "cn-hangzhou"
    Domains = ["test:sample.com"]
    Password = "node-password"
